language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
install: skip

stages:
  - name: Get Maven Project information
  - name: Build, Test and Verify with Maven
  - name: Deploy and make Site
    if: type = push AND branch =~ /^((develop|master)|((release|hotfix|support)\/(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?))$/

jobs:
  include:
    - stage: Get Maven Project information
      name: Get groupId
      script: echo $(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout --file pom.xml --settings .github/workflows/settings.xml)
    - script: echo $(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout --file pom.xml --settings .github/workflows/settings.xml)
      name: Get artifactId
    - script: echo $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout --file pom.xml --settings .github/workflows/settings.xml)
      name: Get version
    - script: echo $(mvn help:evaluate -Dexpression=project.packaging -q -DforceStdout --file pom.xml --settings .github/workflows/settings.xml)
      name: Get packaging

    - stage: Build, Test and Verify with Maven
      script:
        - mvn -U clean compile -Pproject-controls-check --file pom.xml --settings .github/workflows/settings.xml
        - mvn -U -Dmaven.main.skip test --file pom.xml --settings .github/workflows/settings.xml
        - mvn -U -Dmaven.main.skip -Dunit.test.skip verify --file pom.xml --settings .github/workflows/settings.xml
        - mvn -U -Dsonar.branch.name=${GITHUB_REF#refs/heads/} -Dsonar.gitlab.commit_sha=${GITHUB_SHA} sonar:sonar --file pom.xml --settings .github/workflows/settings.xml

    - stage: Deploy and make Site
      name: Publish to GitHub Packages Apache Maven
      script:
        - mvn -U -Dmaven.main.skip -Dunit.test.skip -Dverify.skip jar:jar@default-jar assembly:single@make-assembly source:jar-no-fork@attach-sources javadoc:jar@attach-javadocs deploy --file pom.xml --settings .github/workflows/settings.xml
        - mvn -U site --file pom.xml --settings .github/workflows/settings.xml
