language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
install: true

script:
  - mvn -U clean compile -Pproject-controls-check --file pom.xml --settings .github/workflows/settings.xml
  - mvn -U -Dmaven.main.skip test --file pom.xml --settings .github/workflows/settings.xml
  - mvn -U -Dmaven.main.skip -Dunit.test.skip verify --file pom.xml --settings .github/workflows/settings.xml
  - mvn -U -Dmaven.main.skip -Dunit.test.skip -Dverify.skip jar:jar@default-jar assembly:single@make-assembly source:jar-no-fork@attach-sources javadoc:jar@attach-javadocs deploy --file pom.xml --settings .github/workflows/settings.xml
  - mvn -U site --file pom.xml --settings .github/workflows/settings.xml
